version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true
    restart: always
