version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./:/var/www
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true
    restart: always
