
services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    command:  /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/backend
  db:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
volumes:
  mysql_data:
